### ISSUE TITLE
Feat: Treat Files and Folders as Object Variables in Custom JavaScript Functions

### ISSUE THREAD

**Issue by HamzaBenyazid** [HamzaBenyazid/obsidian-live-variables#34]
**Description:**

To enhance the flexibility of the "Live Variables" plugin, I propose allowing entire files and folders to be treated as object variables. This feature would enable users to access all variables within a file or a collection of files (folder) through a single argument in custom JavaScript functions.

**Use Cases:**

1. **File as an Object Variable:**
   - Access all variables defined in a file's frontmatter collectively, simplifying data management in custom functions.

2. **Folder as an Object Variable:**
   - Manage variables from all notes within a folder through a single function argument, facilitating batch processing and data aggregation.

3. **Vault as an Object Variable:**
   - Access and manage variables across all notes in the vault, enabling global operations and analyses.

**Example:**

Assume the following notes with frontmatter variables:

- **Note 1 (`note1.md`):**
```yaml
  ---
  title: "Note 1"
  author: "Author A"
  ---
```
- **Note 2 (`note2.md`):**
```yaml
---
title: "Note 2"
author: "Author B"
---
```

- **Folder (`Research`) containing:**
   - **Note 3 (`note3.md`):**
```yaml
---
title: "Note 3"
author: "Author C"
---
```
With this feature, a custom JavaScript function can process all variables within a file, folder, or the entire vault.

**Custom JavaScript Function Example:**
```js
(entity) => {
  // Iterate over each variable in the entity
  for (const [key, value] of Object.entries(entity)) {
    console.log(`${key}: ${value}`);
  }
}
```

**Usage:**

1. File Level:
   - Pass the file `note1` variable to the function:
   - Output:
    ```yaml
    title: Note 1
    author: Author A
    ```

2. Folder Level:
   - Pass the folder `Research` variable to the function:
   - Output:
    ```yaml
    note3:
      title: Note 3
      author: Author C
    ```

3. Vault Level:
   - Pass the `vault` variable to the function:
   - Output:
    ```yaml
    note1:
      title: Note 1
      author: Author A
    note2:
      title: Note 2
      author: Author B
    note3:
      title: Note 3
      author: Author C
    ```

Implementing this feature would streamline variable management within Obsidian, allowing bulk access and manipulation through custom functions.
